// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config
:page-layout: guide
:page-duration: 30 minutes
:page-date: 2017-11-?
:page-description: Learn how to use the MicroProfile Config specification to build an application
:page-tags: ['REST', 'MicroProfile', 'Configuration', 'CDI']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Externalizing configuration data with MicroProfile Configuration

Learn how to use the MicroProfile Config specification to build an application. MicroProfile Config integrates configurations for MicroProfile applications.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to aggregate multiple configuration sources and merge configuration values.
Externalize configuration data for an application, add MicroProfile Config into a MicroProfile application by CDI injection, enable
dynamic configuration injection, and assign priorities to different configuration sources. In addition,
you will define a custom configuration source that is more flexible and can override configuration values
for the application.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

When you begin, you can access two microservices to test availability:

* `http://localhost:9080/inventory/hosts`

* `http://localhost:9080/system/properties`

In addition, one service retrieves configuration information that is specific to this guide:

* `http://localhost:9080/inventory/config/all`


// =================================================================================================
// Injecting configuration into the application
// =================================================================================================
== Injecting configuration into the application

Access the local `microprofile-config.properties` configuration file in the `start/src/main/resources/META-INF` directory. This configuration file is the default configuration source for an application that uses MicroProfile Config.

Open the configuration file, which contains the `io.openliberty.guides.microprofile.inventory.inMaintenance` configuration property. This property determines whether the inventory service is in maintenance or not.

[source, java, indent=0, role="no_copy"]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=inventory-in-maintenance]
----

The `io.openliberty.guides.microprofile.port` property determines the port number of the REST service.
[source, java, indent=0, role="no_copy"]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=port-number]
----

Access the partially implemented `InventoryConfig` Java class in the `start/src/main/java/io/openliberty/guides/microprofile` directory.

Open the `InventoryConfig.java` file and add the following configuration injection:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryConfig.java[tags=config]
----

The first `@Inject` annotation injects the Config object, which is request scoped.

The second `@Inject` annotation injects the port number directly, the injection value is static and fixed on application starting.

The third `@Inject` annotation injects the `io.openliberty.guides.microprofile.inventory.inMaintenance` configuration property, a dynamic injection that uses the `Provider<>` interface, which forces the program to retrieve the `inMaintenance` value just in time.

Add the `getPortNumber()` class method. This method is static because `portNumber` is a static property.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryConfig.java[tags=getPortNumber]
----

Add the `isInMaintenance()` class method as shown in the following example:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryConfig.java[tags=isInMaintenance]
----

Every time that you invoke the `inMaintenance.get()` method, the `Provider<>` interface picks up the
latest value of the `io.openliberty.guides.microprofile.inventory.inMaintenance` property from configuration sources.

Open the `InventoryResource.java` file. Instead of hardcoding `9080`, get the port number from the configuration.
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java[tags=config-port]
----

Open the `InventoryResource.java` file. Inject the `InventoryConfig` object to modify the existed class.
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=config-injection]
----
Use the `inventoryConfig.isInMaintenance()` class method to determine whether the inventory service is in maintenance
or not according to the configuration. If you set the `io.openliberty.guides.microprofile.inventory.inMaintenance` property to `true` by configuration, the inventory service returns the message, `Service is temporarily down for maintenance`.
Modify the existed class:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=config-methods]
----

To use the MicroProfile Config feature, add the required dependency to the `start/pom.xml` file:

[source, xml, indent=0]
----
include::finish/pom.xml[tags=config]
----

Also add the `mp-config` feature to the `liberty/config/server.xml` file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=config]
----

// =================================================================================================
// Ordering multiple configuration sources
// =================================================================================================
== Ordering multiple configuration sources

Out of the following three configuration sources, the configuration source with the highest `config_ordinal` value overrides the other configuration values when a value conflict for a configuration property occurs.

* System properties has a default ordinal of 400.
* Environment variables has a default ordinal of 300.
* The `META-INF/microprofile-config.properties` configuration property file on the classpath has a default ordinal of 100.

The current value of the `config_ordinal` source in the `META-INF/microprofile-config.properties` file is set to `600` instead of the default ordinal of `100`. Therefore, the `META-INF/microprofile-config.properties` file gets the highest priority to override any other configuration values.

[source, indent=0, role="no_copy"]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=ordinal]
----

// =================================================================================================
// Creating custom configuration sources
// =================================================================================================
== Creating custom configuration sources

Now you have a `CustomConfigSource.json` file that is located outside of your application
and peers into the `pom.xml` file. Transform the data object from the JSON file to become the configuration values for your application.

In addition to the three default configuration sources, you can create custom configuration sources by
implementing the `org.eclipse.microprofile.config.spi.ConfigSource` interface and using the `java.util.ServiceLoader` mechanism.

Open the custom configuration `start/src/main/java/io/openliberty/guides/config/CustomConfigSource.java` source file.
Add the following content to override the `ConfigSource` class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java[tags=customConfig]
----

The `setProperties()` private method reads the key value pairs from the `CustomConfigSource.json` JSON file and writes the information into the configuration source.

To register the custom configuration source, add the full class name in the `META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource` file:

[source, java, indent=0]
----
include::finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource[tags=register]
----


// =================================================================================================
// Building the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see the new application in action, run the Maven `liberty:start-server` command from the `start` directory:

[source, role="no_copy"]
----
$ mvn liberty:start-server
----

Once the server is running, you can find the services at the following locations:

* `http://localhost:9080/inventory/config/all`
* `http://localhost:9080/inventory/hosts`
* `http://localhost:9080/system/properties`

At first, the `config_ordinal` value of the custom configuration source is set to `500`.
A value of `500` does not override configuration values of the default `microprofile-config.properties` source, which has a `config_ordinal` value of `600`.

However, you can manually change the `config_ordinal` value in the `CustomConfigSource.json` file. Your change is added dynamically, and you do not need to restart the server.

Play with this application by changing configuration values for each property in the `CustomConfigSource.json` file.
Refresh the pages to see the dynamic changes.


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Add the following test cases to the corresponding locations in the `start/src/test/java/it/io/openliberty/guides/microprofile/ConfigurationTest.java` file:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/ConfigurationTest.java[tags=testInitialServiceStatus()]
----

The `testInitialServiceStatus()` test case reads the value of the `io.openliberty.guides.microprofile.inventory.inMaintenance` configuration property in the file `META-INF/microprofile-config.properties` and checks the HTTP response of the inventory service. If the configuration value is `false`, the service returns a valid response. Otherwise,
the service returns a message that says, `Service is temporarily down for maintenance`.


[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/ConfigurationTest.java[tags=testOverrideConfigProperty()]
----

Because the `META-INF/microprofile-config.properties` default source has the highest ordinal value of `600` in the beginning,
the `testOverrideConfigProperty()` test case first checks that the `http://localhost:9080/inventory/config/all` microservice contains
the `io.openliberty.guides.microprofile.inventory.testConfigOverwrite` test property with the `DefaultSource` value, which is set by this default file.
Then, the test changes the ordinal value of the custom configuration source from `500` to `700` so that the custom configuration source becomes the highest priority. In the end, the `CustomSource` value overrides the test property.


[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/ConfigurationTest.java[tags=testPutServiceInMaintenance()]
----

Because the `io.openliberty.guides.microprofile.inventory.inMaintenance` configuration property is set to `false` by default, the `testPutServiceInMaintenance()` test case first checks that the inventory service is not in maintenance in the beginning. Next,
this test increases the priority of the custom configuration source and switches the value of the `io.openliberty.guides.microprofile.inventory.inMaintenance` configuration property
to `true`. In the end, the inventory service returns a message that says, `Service is temporarily down for maintenance`.


Add the test suite method:
[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/ConfigurationTest.java[tags=testSuite]
----

=== Running the tests

Reset the `microprofile-config.properties` file and the `CustomConfigSource.json` file to the following original values before you run tests.
Some of the test cases assume the default configuration.
[source, java, indent=0]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=all-props]
----

```
{
    "config_ordinal": 500,
    "io.openliberty.guides.microprofile.inventory.inMaintenance": false,
    "io.openliberty.guides.microprofile.system.inMaintenance": false,
    "io.openliberty.guides.microprofile.inventory.testCustomConfigProperty": "OpenLiberty",
    "io.openliberty.guides.microprofile.inventory.testConfigOverwrite": "CustomSource"
}

```

To rebuild and run the tests, navigate to the `start` directory and run the `mvn clean install` command
from the command line:

[source, role="no_copy"]
----
# Stop the server if it is still running from previous steps:
$ mvn liberty:stop-server

# Next, execute the command:
$ mvn clean install
----

The program might take some time to execute the tests. If the tests pass, you receive the following output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.microprofile.ConfigurationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.324 sec - in it.io.openliberty.guides.microprofile.ConfigurationTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

----

== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Config and Open Liberty.

include::{common-includes}/finish.adoc[]
