// Copyright (c) 2017, 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config
:page-layout: guide
:page-duration: 20 minutes
:page-releasedate: 2018-03-09
:page-description: Learn how to use the MicroProfile Config specification to externalize configuration data for an application
:page-tags: ['REST', 'MicroProfile', 'Config', 'ConfigProperty', 'Custom ConfigSource', 'Dynamic Configuration Injection', 'microservices']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Configuring microservices

Learn how to provide external configuration to microservices using MicroProfile Config.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to externalize and inject both static and dynamic configuration properties for microservices using MicroProfile Config.

You will learn to aggregate multiple configuration sources, assign prioritization values to these sources, merge configuration values, and create custom configuration sources.

The application that you will be working with is an `inventory` service which stores the information about various JVMs running on different hosts.
Whenever a request is made to the `inventory` service to retrieve the JVM
system properties of a particular host, the `inventory` service will communicate with the `system`
service on that host to get these system properties. You will add configuration properties to simulate if a service is down for maintenance.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished inventory application. Feel
free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

After starting the application, you can access the following two microservices to test their availability:

* `http://localhost:9080/system/properties` retrieves the information for a specific host

* `http://localhost:9080/inventory/systems` retrieves the information for a list of all previously registered hosts

In addition, you can access a third microservice, which retrieves and aggregates all of the configuration properties and sources that have been added throughout this guide. This is available at:

* `http://localhost:9080/config`

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.


// =================================================================================================
// Ordering multiple configuration sources
// =================================================================================================
== Ordering multiple configuration sources

MicroProfile Config combines configuration properties from multiple sources, each known as a _ConfigSource_. Each ConfigSource has a specified priority, defined by its _config_ordinal_ value.

A higher ordinal value means that the values taken from this ConfigSource will override values from ConfigSources with a lower ordinal value.

There are three default configuration sources as following:

* System properties has a default ordinal of 400. (e.g. `bootstrap.properties` file)
* Environment variables has a default ordinal of 300. (e.g. `server.env` file)
* The `META-INF/microprofile-config.properties` configuration property file on the classpath has a default ordinal of 100.

Access the `src/main/resources/META-INF/microprofile-config.properties` local configuration file. This configuration file is the default configuration source for an application that uses MicroProfile Config.

[source, java, indent=0, role="no_copy"]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=all-props]
----

// =================================================================================================
// Injecting static configuration
// =================================================================================================
== Injecting static configuration

The MicroProfile Health API was added as a dependency to your `pom.xml` file. Look for the dependency with the `microprofile-config-api` group ID.
This feature allows you to use the MicroProfile Config API to externalize configurations for your microservices.
The `mpConfig-1.1` feature is also enabled in the `src/main/liberty/config/server.xml` file.

Now navigate to the `src/main/resources/META-INF/microprofile-config.properties` local configuration file to check some static configuration.
This configuration file is the default configuration source for an application that uses MicroProfile Config.

The `io_openliberty_guides_port_number` property that has already been defined in this file, determines the port number of the REST service.

To use this configuration property, create a `src/main/java/io/openliberty/guides/inventory/InventoryConfig.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=**;!copyright;!build-in-converter;!custom-converter;!isInMaintenance;!getEmail]
----

Inject the `io_openliberty_guides_port_number` property, and add the `getPortNumber()` class method to the `InventoryConfig.java` file.

The `@Inject` annotation injects the port number directly, the injection value is static and fixed on application starting.

The `getPortNumber()` method directly returns the value of `portNumber` because it has been injected.

// =================================================================================================
// Injecting dynamic configuration
// =================================================================================================
== Injecting dynamic configuration

Note that three default config sources mentioned above are static and fixed on application starting, so the properties within them cannot be modified while the server is running.
However, you can externalize configuration data out of the application package, through the creation of custom configuration sources, so that the service updates configuration changes dynamically.

// =================================================================================================
// Creating custom configuration sources
// =================================================================================================
=== Creating custom configuration sources

Custom configuration sources can be created by implementing the `org.eclipse.microprofile.config.spi.ConfigSource` interface and using the `java.util.ServiceLoader` mechanism.

A `CustomConfigSource.json` JSON file has already been created in the `resources` directory. This JSON file simulates a remote configuration resource in real life.
This file contains 4 custom config properties and has an ordinal of `50`.
To use these properties in the application, the data object needs to be transformed from this JSON file to the configuration for your application.

To link this JSON file to your application, create a `CustomConfigSource` class in the `src/main/java/io/openliberty/guides/config/CustomConfigSource.java` file. Add the following content to implement the `ConfigSource` interface:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java[tags=customConfig]
----

The `getProperties()` method reads the key value pairs from the `resources/CustomConfigSource.json` JSON file and writes the information into a map.

Last but important, register the custom configuration source. Create a `src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource` file. Add the following fully qualified class name of the configuration source into it:

[source, java, indent=0]
----
include::finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource[tags=register]
----

// =================================================================================================
// Enabling dynamic configuration injection
// =================================================================================================
=== Enabling dynamic configuration injection

Now that the custom configuration source has successfully been set up, you can enable dynamic configuration injection of the properties being set in this ConfigSource.
To enable this dynamic injection, first access the partially implemented Java class in the `src/main/java/io/openliberty/guides/inventory/InventoryConfig.java` file,
inject the `io_openliberty_guides_inventory_inMaintenance` property, and add the `isInMaintenance()` class method. Simply copy all the following code and replace the contents of the file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=**;!copyright;!custom-converter;!getEmail]
----

The `@Inject` and `@ConfigProperty` annotations inject the `io_openliberty_guides_inventory_inMaintenance` configuration property from the `CustomConfigSource.json` file.
The `Provider<>` interface used, forces the service to retrieve the inMaintenance value just in time. This retrieval of the value just in time makes the config injection dynamic and able to change without having to restart the application.

Every time that you invoke the `inMaintenance.get()` method, the `Provider<>` interface picks up the
latest value of the `io_openliberty_guides_inventory_inMaintenance` property from configuration sources.

// =================================================================================================
// Creating custom converters
// =================================================================================================
== Creating custom converters
Configuration values are purely Strings. MicroProfile Config API has built-in converters that automatically converts configured Strings into target types such as `int`, `Integer`, `boolean`, `Boolean`, `float`, `Float`, `double` and `Double`.
Therefore, in the previous section, it is type-safe to directly set the variable type to `Provider<Boolean>`.

To convert configured Strings to an arbitrary class type, such as the `Email` class type, create a `src/main/java/io/openliberty/guides/config/Email.java` file:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/config/Email.java[tags=email]
----

To use this `Email` class type, add a custom converter by implementing the generic interface `org.eclipse.microprofile.config.spi.Converter<T>`.
The Type parameter of the interface is the target type the String is converted to.

Create a `src/main/java/io/openliberty/guides/config/CustomEmailConverter.java` file, and add the following content to implement the `Converter<T>` interface:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/config/CustomEmailConverter.java[tags=customConfig]
----

To register your implementation, create a `src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter` file. Add the following fully qualified class name of the custom converter into it:
[source, java, indent=0]
----
include::finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter[tags=register]
----

To use the custom `Email` converter, open the `src/main/java/io/openliberty/guides/inventory/InventoryConfig.java` file, inject the `io_openliberty_guides_email` property, and add the `getEmail()` method. Simply copy all the following code and replace the contents of the file:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=config-class]
----

// =================================================================================================
// Adding configuration to the service
// =================================================================================================
== Adding configuration to the microservice

To use externalized configuration in the `inventory` service, open the `src/main/java/io/openliberty/guides/inventory/InventoryResource.java` file.
Simply copy all the following code and replace the contents of the file:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=config-methods]
----

To add configuration to the `inventory` service, the `InventoryConfig` object is injected to the existing class.

The port number from the configuration is retrieved by the `inventoryConfig.getPortNumber()` method and passed to the `manager.get()` method as a parameter.

To determine whether the inventory service is in maintenance or not (according to the configuration value), `inventoryConfig.isInMaintenance()` class method is used.
If you set the `io_openliberty_guides_inventory_inMaintenance` property to `true` in the configuration, the inventory service returns the message, `ERROR: Service is currently in maintenance`, along with the contact email.
The email configuration value can be get by calling `inventoryConfig.getEmail()` method.


// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Once the server is running, the following two microservices should be available to access:

* `http://localhost:9080/system/properties`

* `http://localhost:9080/inventory/systems`


You can find the service that retrieves configuration information that is specific to this guide at the following location:

* `http://localhost:9080/config`


At first, the `config_ordinal` value of the custom configuration source is set to `50`.
A value of `50` does not override configuration values of the default `microprofile-config.properties` source, which has a `config_ordinal` value of `100`.

However, you can manually change the `config_ordinal` value to a larger number in the `resources/CustomConfigSource.json` file.

Your changes are added dynamically, and you do not need to restart the server.
Refresh `http://localhost:9080/config` to see the dynamic changes.

Play with this application by changing configuration values for each property in the `resources/CustomConfigSource.json` file.

For example, change `io_openliberty_guides_inventory_inMaintenance` from `false` to `true`, then try to access `http://localhost:9080/inventory/systems` again.
The following message displays: `ERROR: Service is currently in maintenance`.

include::{common-includes}/mvnpackage.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Create a `src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java` file and add the following code:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java[tags=test]
----

The `testInitialServiceStatus()` test case reads the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property in the file `META-INF/microprofile-config.properties` and checks the HTTP response of the inventory service.
If the configuration value is `false`, the service returns a valid response. Otherwise, the service returns the following message: `ERROR: Service is currently in maintenance`.


Because the `META-INF/microprofile-config.properties` default source has the ordinal value of `100` in the beginning,
the `testOverrideConfigProperty()` test case first checks that the `http://localhost:9080/config` microservice contains
the `io_openliberty_guides_testConfigOverwrite` test property with the `DefaultSource` value, which is set by this default file.
Then, the test changes the ordinal value of the custom configuration source from `50` to `150` so that the custom configuration source has the higher priority. In the end, the `CustomSource` value overrides the test property.


Because the `io_openliberty_guides_inventory_inMaintenance` configuration property is set to `false` by default, the `testPutServiceInMaintenance()` test case first checks that the inventory service is not in maintenance in the beginning.
Next, this test increases the priority of the custom configuration source and switches the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property to `true`.
In the end, the inventory service returns the following message: `ERROR: Service is currently in maintenance`.

In addition, a few endpoint tests have been provided for you to test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you must have introduced a bug into the code.
Reminder that you must register the custom configuration source and custom converter in the `src/main/resources/META-INF/services/` directory, if you miss to complete these steps, the tests will fail.

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.config.ConfigurationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.729 sec - in it.io.openliberty.guides.config.ConfigurationTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.477 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in it.io.openliberty.guides.system.SystemEndpointTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

----

To see whether the tests detect a failure, remove the configuration resetting line in the `setup()` method of the `ConfigurationTest.java` file.
Then manually change some configuration values in the `resources/CustomConfigSource.json` file.
Re-run the Maven build. You will see a test failure occur.

== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Config and Open Liberty.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and
expand on top what you built in this guide.

include::{common-includes}/finish.adoc[]
