// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to use the MicroProfile Config specification to externalize configuration data for an application
:page-tags: ['REST', 'MicroProfile', 'Config', 'ConfigSource', 'ConfigProperty']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Configuring Microservices using MicroProfile Config

Learn how to use the MicroProfile Config specification to externalize configuration data for an application.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to externalize and inject both static and dynamic configuration properties from microservices using MicroProfile Config.

You’ll learn to aggregate multiple configuration sources, assign prioritization values to these sources, merge configuration values, and create custom configuration sources.

After starting the application, you will be able to access the following two microservices to test their availability:

* `http://localhost:9080/system/properties` retrieves the information for a specific host

* `http://localhost:9080/inventory/hosts` retrieves the information for a list of all previously registered hosts

To learn more about these two microservices and how you can write the MicroProfile application, see
https://openliberty.io/guides/microprofile-intro.html[Creating a MicroProfile application].

In addition, you will be able to access a third microservice, which retrieves and aggregates all of the configuration properties and sources that have been added throughout this guide. This is available at:

* `http://localhost:9080/config`

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Ordering multiple configuration sources
// =================================================================================================
== Ordering multiple configuration sources

MicroProfile Config combines configuration properties from multiple sources, each known as a _ConfigSource_. Each ConfigSource has a specified priority, defined by its _config_ordinal_ value.

A higher ordinal value means that the values taken from this ConfigSource will override values from ConfigSources with a lower ordinal value.

There are three default configuration sources as following:

* System properties has a default ordinal of 400. (e.g. `bootstrap.properties` file)
* Environment variables has a default ordinal of 300. (e.g. `server.env` file)
* The `META-INF/microprofile-config.properties` configuration property file on the classpath has a default ordinal of 100.

Access the local `microprofile-config.properties` configuration file in the `start/src/main/resources/META-INF` directory. This configuration file is the default configuration source for an application that uses MicroProfile Config.

[source, java, indent=0, role="no_copy"]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=all-props]
----

// =================================================================================================
// Injecting configuration into the application
// =================================================================================================
== Injecting static configuration into the application

Begin by enabling the MicroProfile Config feature in your `pom.xml` file. This feature allows you to use the MicroProfile Config API to externalize configuration data.

Navigate to the `start/pom.xml` file and add the required dependency:
[source, xml, indent=0]
----
include::finish/pom.xml[tags=config]
----

The mp-config feature also needs to be added to the `start/src/main/liberty/config/server.xml` file:
[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=config]
----

Now that the MicroProfile Config feature has been enabled, navigate to the local  `microprofile-config.properties` configuration file in the `start/src/main/resources/META-INF` directory to check some static configuration.
This configuration file is the default configuration source for an application that uses MicroProfile Config.

The `io_openliberty_guides_port_number` property that has already been defined in this file, determines the port number of the REST service.
[source, java, indent=0, role="no_copy"]
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=inventory-port-number]
----

To use this configuration property, create an `InventoryConfig.java` file in the `start/src/main/java/io/openliberty/guides/inventory` directory.

Add the following code to the `InventoryConfig.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=config-class;port-number;getPortNumber]
----

The `@Inject` annotation injects the port number directly, the injection value is static and fixed on application starting.

The `getPortNumber()` method directly returns the value of `portNumber` because it has been injected.


Open the `InventoryResource.java` file. Inject the `InventoryConfig` object to modify the existing class.
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=config-injection]
----

Modify the `getPropertiesForHost()` service. Get the port number from the configuration and pass this value to the `manager.get()` method to get the system properties.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=config-port]
----


// =================================================================================================
// Creating custom configuration sources
// =================================================================================================
== Creating custom configuration sources

Note that three default config sources mentioned above are static and fixed on application starting, so the properties within them cannot be modified while the server is running.
However, you can externalize configuration data out of the application package, through the creation of custom configuration sources, so that the service updates configuration changes dynamically.

Custom configuration sources can be created by implementing the `org.eclipse.microprofile.config.spi.ConfigSource` interface and using the `java.util.ServiceLoader` mechanism.

In the starting repo for this guide a `CustomConfigSource.json` JSON file has already been created outside of the application (`start/resources/`).
This file contains 4 custom config properties and has an ordinal of `50`.
To use these properties in the application, the data object needs to be transformed from this JSON file to the configuration for your application.

To link this JSON file to your application, create a `CustomConfigSource.java` file in the `start/src/main/java/io/openliberty/guides/config` directory and add the following content to override the `ConfigSource` interface:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java[tags=customConfig]
----

The `setProperties()` private method reads the key value pairs from the `CustomConfigSource.json` JSON file and writes the information into a map.

To register the custom configuration source, create the `start/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource` file and add the full class name into it:

[source, java, indent=0]
----
include::finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource[tags=register]
----


// =================================================================================================
// Enabling dynamic configuration injection
// =================================================================================================
== Enabling dynamic configuration injection

Now that the custom configuration source has successfully been set up, you can enable dynamic configuration injection of the properties being set in this ConfigSource.
To enable this dynamic injection, first access the partially implemented `InventoryConfig.java` Java class in the `start/src/main/java/io/openliberty/guides/inventory` directory,
add the following configuration injection and the `isInMaintenance()` class method as shown in the following example:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=build-in-converter]
----

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=isInMaintenance]
----

The `@Inject` and `@ConfigProperty` annotations inject the `io_openliberty_guides_inventory_inMaintenance` configuration property from the `CustomConfigSource.json` file.
The `Provider<>` interface used, forces the service to retrieve the inMaintenance value just in time. This retrieval of the value just in time makes the config injection dynamic and able to change without having to restart the application.

Every time that you invoke the `inMaintenance.get()` method, the `Provider<>` interface picks up the
latest value of the `io_openliberty_guides_inventory_inMaintenance` property from configuration sources.

// =================================================================================================
// Creating custom converters
// =================================================================================================
== Adding custom converters
Configuration values are purely Strings. MicroProfile Config API has built-in converters that automatically converts configured Strings into target types such as `int`, `Integer`, `boolean`, `Boolean`, `float`, `Float`, `double` and `Double`.
Therefore, in the previous section, it is type-safe to directly set the variable type to `Provider<Boolean>`.

To convert configured Strings to an arbitrary class type, such as the `Email` class type, create an `Email` class file in the `start/src/main/java/io/openliberty/guides/config` directory.
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/config/Email.java[tags=email]
----

To use this `Email` class type, add a custom converter by implementing the generic interface `org.eclipse.microprofile.config.spi.Converter<T>`.
The Type parameter of the interface is the target type the String is converted to.

Create a `CustomEmailConverter.java` file in the `start/src/main/java/io/openliberty/guides/config` directory.
Add the following content to override the `Converter<T>` interface:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/config/CustomEmailConverter.java[tags=customConfig]
----

To register your implementation, create the `start/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter` file and add the fully qualified class name of the custom converter into it:
[source, java, indent=0]
----
include::finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter[tags=register]
----

To use the custom `Email` converter, open the `InventoryConfig.java` file, inject the `io_openliberty_guides_email` property, and add the `getEmail()` method:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=custom-converter;getEmail]
----

To determine whether the inventory service is in maintenance or not (according to the configuration value), use the `inventoryConfig.isInMaintenance()` class method.
If you set the `io_openliberty_guides_inventory_inMaintenance` property to `true` in the configuration, the inventory service returns the message, "Service is temporarily down for maintenance", along with the contact email.
The email configuration value can be get by calling `inventoryConfig.getEmail()`.

Open the `InventoryResource.java` file. Modify the existing class to finalize the code as the following:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=config-methods]
----


// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Once the server is running, the following two microservices should be available to access:

* `http://localhost:9080/inventory/hosts`

* `http://localhost:9080/system/properties`


You can find the service that retrieves configuration information that is specific to this guide at the following location:

* `http://localhost:9080/config`


At first, the `config_ordinal` value of the custom configuration source is set to `50`.
A value of `50` does not override configuration values of the default `microprofile-config.properties` source, which has a `config_ordinal` value of `100`.

However, you can manually change the `config_ordinal` value to a larger number in the `CustomConfigSource.json` file.

Your changes are added dynamically, and you do not need to restart the server.
Refresh `http://localhost:9080/config` to see the dynamic changes.

Play with this application by changing configuration values for each property in the `CustomConfigSource.json` file.

For example, change `io_openliberty_guides_inventory_inMaintenance` from `false` to `true`, then try to access `http://localhost:9080/inventory/hosts` again.
The following message displays: `Service is temporarily down for maintenance`.

include::{common-includes}/mvnpackage.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Create a `ConfigurationTest.java` file in the `start/src/test/java/it/io/openliberty/guides/config` directory and add the following code:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java[tags=test]
----

The `testInitialServiceStatus()` test case reads the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property in the file `META-INF/microprofile-config.properties` and checks the HTTP response of the inventory service.
If the configuration value is `false`, the service returns a valid response. Otherwise, the service returns the following message: `Service is temporarily down for maintenance`.


Because the `META-INF/microprofile-config.properties` default source has the ordinal value of `100` in the beginning,
the `testOverrideConfigProperty()` test case first checks that the `http://localhost:9080/config` microservice contains
the `io_openliberty_guides_testConfigOverwrite` test property with the `DefaultSource` value, which is set by this default file.
Then, the test changes the ordinal value of the custom configuration source from `50` to `150` so that the custom configuration source has the higher priority. In the end, the `CustomSource` value overrides the test property.


Because the `io_openliberty_guides_inventory_inMaintenance` configuration property is set to `false` by default, the `testPutServiceInMaintenance()` test case first checks that the inventory service is not in maintenance in the beginning.
Next, this test increases the priority of the custom configuration source and switches the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property to `true`.
In the end, the inventory service returns the following message: `Service is temporarily down for maintenance`.

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.config.ConfigurationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.322 sec - in it.io.openliberty.guides.config.ConfigurationTest
Running it.io.openliberty.guides.inventory.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.307 sec - in it.io.openliberty.guides.inventory.EndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

----

== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Config and Open Liberty.

include::{common-includes}/finish.adoc[]
