// Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2018-03-09
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to use the MicroProfile Config specification to externalize configuration data for an application.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:guide-author: Open Liberty
= Configuring microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to provide external configuration to microservices using MicroProfile Config.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to externalize and inject both static and dynamic configuration properties for microservices using MicroProfile Config.

You will learn to aggregate multiple configuration sources, assign prioritization values to these sources, merge configuration values, and create custom configuration sources.

The application that you will be working with is an `inventory` service which stores the information about various JVMs running on different hosts.
Whenever a request is made to the `inventory` service to retrieve the JVM
system properties of a particular host, the `inventory` service will communicate with the `system`
service on that host to get these system properties. You will add configuration properties to simulate if a service is down for maintenance.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished inventory application. Feel
free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following
Maven goals to build the application and run it inside Open Liberty:

[role=command]
```
cd finish
mvn install liberty:start-server
```

After starting the application, you can access the following two microservices to test their availability:

* http://localhost:9080/system/properties[http://localhost:9080/system/properties^] retrieves the information for a specific host

* http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] retrieves the information for a list of all previously registered hosts

In addition, you can access a third microservice, which retrieves and aggregates all of the configuration properties and sources that have been added throughout this guide. This is available at:

* http://localhost:9080/config[http://localhost:9080/config^]

Once you are done checking out the application, stop the Open Liberty server:

[role=command]
```
mvn liberty:stop-server
```

// =================================================================================================
// Ordering multiple configuration sources
// =================================================================================================
== Ordering multiple configuration sources

Now, navigate to the `start` directory to begin.

MicroProfile Config combines configuration properties from multiple sources, each known as a _ConfigSource_. Each ConfigSource has a specified priority, defined by its _config_ordinal_ value.

A higher ordinal value means that the values taken from this ConfigSource will override values from ConfigSources with a lower ordinal value.

There are three default configuration sources as following:

* System properties has a default ordinal of 400. (e.g. `bootstrap.properties` file)
* Environment variables has a default ordinal of 300. (e.g. `server.env` file)
* The [hotspot=1]`META-INF/microprofile-config.properties` configuration property file on the classpath has a default ordinal of 100.

Access the [hotspot]`src/main/resources/META-INF/microprofile-config.properties` local configuration file. This configuration file is the default configuration source for an application that uses MicroProfile Config.

microprofile-config.properties
[source, properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=**;!copyright]
----

// =================================================================================================
// Injecting static configuration
// =================================================================================================
== Injecting static configuration

The MicroProfile Config API was added as a dependency to your [hotspot file=0]`pom.xml` file. Look for the dependency with the [hotspot=71 file=0]`mpConfig` artifact ID.
This feature allows you to use the MicroProfile Config API to externalize configurations for your microservices.
The [hotspot=8 file=1]`mpConfig` feature is also enabled in the [hotspot file=1]`src/main/liberty/config/server.xml` file.

pom.xml
[source,xml,linenums,role="code_column"]
----
include::finish/pom.xml[tags=**]
----

server.xml
[source,xml,linenums,role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[tags=**]
----

Now navigate to the [hotspot file=2]`src/main/resources/META-INF/microprofile-config.properties` local configuration file to check some static configuration.
This configuration file is the default configuration source for an application that uses MicroProfile Config.

The [hotspot=2 file=2]`io_openliberty_guides_port_number` property that has already been defined in this file, determines the port number of the REST service.

microprofile-config.properties
[source, properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[tags=**;!copyright]
----

To use this configuration property, 
[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryConfig.java` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryConfig.java`
----
InventoryConfig.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=**;!copyright;!build-in-converter;!custom-converter;!isInMaintenance;!getEmail]
----

Inject the [hotspot=13 file=3]`io_openliberty_guides_port_number` property, and add the [hotspot=16-18 file=3]`getPortNumber()` class method to the [hotspot file=3]`InventoryConfig.java` file.

The [hotspot=12 file=3]`@Inject` annotation injects the port number directly, the injection value is static and fixed on application starting.

The [hotspot=16-18 file=3]`getPortNumber()` method directly returns the value of `portNumber` because it has been injected.

// =================================================================================================
// Injecting dynamic configuration
// =================================================================================================
== Injecting dynamic configuration

Note that three default config sources mentioned above are static and fixed on application starting, so the properties within them cannot be modified while the server is running.
However, you can externalize configuration data out of the application package, through the creation of custom configuration sources, so that the service updates configuration changes dynamically.

// =================================================================================================
// Creating custom configuration sources
// =================================================================================================
=== Creating custom configuration sources
CustomConfigSource.json
[source, Json, linenums, role='code_column']
----
include::finish/resources/CustomConfigSource.json[tags=**]
----

Custom configuration sources can be created by implementing the `org.eclipse.microprofile.config.spi.ConfigSource` interface and using the `java.util.ServiceLoader` mechanism.

A [hotspot file=0]`CustomConfigSource.json` JSON file has already been created in the `resources` directory. This JSON file simulates a remote configuration resource in real life.
This file contains 4 custom config properties and has an ordinal of [hotspot=0 file=2]`150`.
To use these properties in the application, the data object needs to be transformed from this JSON file to the configuration for your application.

To link this JSON file to your application and to implement the `ConfigSource` interface,

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `CustomConfigSource` class.#
`src/main/java/io/openliberty/guides/config/CustomConfigSource.java`
----
CustomConfigSource.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java[tags=**;!copyright]
----

The [hotspot=46-77 file=1]`getProperties()` method reads the key value pairs from the `resources/CustomConfigSource.json` JSON file and writes the information into a map.

Last but important, register the custom configuration source. 

[role="code_command hotspot file=2", subs="quotes"]
----
#Create the configuration file.#
`src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource`
----

org.eclipse.microprofile.config.spi.ConfigSource
[source, Java, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource[tags=**]
----

Add the fully qualified class name of the configuration source into it.



// =================================================================================================
// Enabling dynamic configuration injection
// =================================================================================================
=== Enabling dynamic configuration injection

Now that the custom configuration source has successfully been set up, you can enable dynamic configuration injection of the properties being set in this ConfigSource.
To enable this dynamic injection, 

[role="code_command hotspot", subs="quotes"]
----
#Replace the `InventoryConfig.java` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryConfig.java`
----
InventoryConfig.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=**;!copyright;!custom-converter;!getEmail]
----
inject the [hotspot=4 file=1]`io_openliberty_guides_inventory_inMaintenance` property, and add the [hotspot=24-26 file=0]`isInMaintenance()` class method. Simply copy all the code and replace the contents of the file.

The [hotspot=16 file=0]`@Inject` and [hotspot=17 file=0]`@ConfigProperty` annotations inject the [hotspot=4 file=1]`io_openliberty_guides_inventory_inMaintenance` configuration property from the [hotspot file=1]`CustomConfigSource.json` file.
The `Provider<>` interface used, forces the service to retrieve the inMaintenance value just in time. This retrieval of the value just in time makes the config injection dynamic and able to change without having to restart the application.

Every time that you invoke the [hotspot=25 file=0s]`inMaintenance.get()` method, the `Provider<>` interface picks up the
latest value of the [hotspot=4 file=1]`io_openliberty_guides_inventory_inMaintenance` property from configuration sources.

CustomConfigSource.json
[source, Json, linenums, role='code_column']
----
include::finish/resources/CustomConfigSource.json[tags=**]
----

// =================================================================================================
// Creating custom converters
// =================================================================================================
== Creating custom converters
Configuration values are purely Strings. MicroProfile Config API has built-in converters that automatically converts configured Strings into target types such as `int`, `Integer`, `boolean`, `Boolean`, `float`, `Float`, `double` and `Double`.
Therefore, in the previous section, it is type-safe to directly set the variable type to `Provider<Boolean>`.

To convert configured Strings to an arbitrary class type, such as the `Email` class type,
[role="code_command hotspot", subs="quotes"]
---- 
#Create the `Email` Class.#
`src/main/java/io/openliberty/guides/config/Email.java`
----
Email.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/config/Email.java[tags=email]
----

To use this [hotspot=3-26 file=0]`Email` class type, add a custom converter by implementing the generic interface `org.eclipse.microprofile.config.spi.Converter<T>`.
The Type parameter of the interface is the target type the String is converted to.

[role="code_command hotspot", subs="quotes"]
----
#Create the `CustomEmailConverter` class.#
`src/main/java/io/openliberty/guides/config/CustomEmailConverter.java`
----
CustomEmailConverter.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/config/CustomEmailConverter.java[tags=**;!copyright]
----

This implements the `Converter<T>` interface.

To register your implementation,
[role="code_command hotspot", subs="quotes"]
----
#Create the configuration file.#
`src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter`
----
org.eclipse.microprofile.config.spi.Converter
[source, Java, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter[tags=**]
----
Add the fully qualified class name of the custom converter into it.

To use the custom [hotspot=10-35]`Email` converter,
[role="code_command hotspot", subs="quotes"]
---- 
#Replace the `InventoryConfig` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryConfig.java`
----
InventoryConfig.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[tags=**;!copyright]
----
Inject the `io_openliberty_guides_email` property, and add the [hotspot=32-34 file=3]`getEmail()` method. Simply copy all the following code and replace the contents of the file.

// =================================================================================================
// Adding configuration to the service
// =================================================================================================
== Adding configuration to the microservice

To use externalized configuration in the `inventory` service, 
[role="code_command hotspot", subs="quotes"]
----
#Replace the `InventoryResource` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----
InventoryResource.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=**;!copyright]
----
To add configuration to the `inventory` service, the [hotspot=25 file=0]`InventoryConfig` object is injected to the existing class.

The port number from the configuration is retrieved by the [hotspot=33 file=0]`inventoryConfig.getPortNumber()` method and passed to the [hotspot=33 file=0]`manager.get()` method as a parameter.

To determine whether the inventory service is in maintenance or not (according to the configuration value), [hotspot=55 file=0]`inventoryConfig.isInMaintenance()` class method is used.
If you set the [hotspot=4 file=1]`io_openliberty_guides_inventory_inMaintenance` property to `true` in the configuration, the inventory service returns the message, `ERROR: Service is currently in maintenance`, along with the contact email.
The email configuration value can be get by calling [hotspot=60 file=0]`inventoryConfig.getEmail()` method.

CustomConfigSource.json
[source, Json, linenums, role='code_column']
----
include::finish/resources/CustomConfigSource.json[tags=**]
----


// =================================================================================================
// Building and running the application
// =================================================================================================

[role=command]
include::{common-includes}/mvnbuild.adoc[]

Once the server is running, the following two microservices should be available to access:

* http://localhost:9080/system/properties[http://localhost:9080/system/properties^]

* http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^]


You can find the service that retrieves configuration information that is specific to this guide at the following location:

* http://localhost:9080/config[http://localhost:9080/config^]


The [hotspot=2 file=0]`config_ordinal` value of the custom configuration source is set to `150`. It overrides configuration values of the default `microprofile-config.properties` source, which has a `config_ordinal` value of `100`.

CustomConfigSource.json
[source, Json, linenums, role='code_column']
----
include::finish/resources/CustomConfigSource.json[tags=**]
----

Play with this application by changing configuration values for each property in the [hotspot file=0]`resources/CustomConfigSource.json` file.
Your changes are added dynamically, and you do not need to restart the server. Refresh http://localhost:9080/config[http://localhost:9080/config^] to see the dynamic changes.

For example, change [hotspot=4 file=0]`io_openliberty_guides_inventory_inMaintenance` from `false` to `true`, then try to access http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] again.
The following message displays: `ERROR: Service is currently in maintenance`.

[role=command]
include::{common-includes}/mvncompile.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

[role="code_command hotspot", subs="quotes"]
----
#Create the `ConfigurationTest` class.#
`src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java`
----
ConfigurationTest.java
[source, Java, linenums, role='code_column']
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java[tags=test]
----

The [hotspot=52-67 file=0]`testInitialServiceStatus()` test case reads the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property in the file `META-INF/microprofile-config.properties` and checks the HTTP response of the inventory service.
If the configuration value is `false`, the service returns a valid response. Otherwise, the service returns the following message: `ERROR: Service is currently in maintenance`.

Because the `io_openliberty_guides_inventory_inMaintenance` configuration property is set to `false` by default, the [hotspot=69-85 file=0]`testPutServiceInMaintenance()` test case first checks that the inventory service is not in maintenance in the beginning.
Next, this test switches the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property to `true`.
In the end, the inventory service returns the following message: `ERROR: Service is currently in maintenance`.

The [hotspot=87-105 file=0]`testChangeEmail()` test case first puts the `inventory` service in maintenance, then it changes the email address in the configuration file. In the end, the `inventory` service should display the error message with the latest email address.

In addition, a few endpoint tests have been provided for you to test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you must have introduced a bug into the code.
Reminder that you must register the custom configuration source and custom converter in the `src/main/resources/META-INF/services/` directory, if you miss to complete these steps, the tests will fail.

[role=command]
include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.config.ConfigurationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.729 sec - in it.io.openliberty.guides.config.ConfigurationTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.477 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in it.io.openliberty.guides.system.SystemEndpointTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

----

To see whether the tests detect a failure, remove the configuration resetting line in the [hotspot=30-37 file=0]`setup()` method of the [hotspot file=0]`ConfigurationTest.java` file.
Then manually change some configuration values in the `resources/CustomConfigSource.json` file.
Re-run the Maven build. You will see a test failure occur.


== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Config in Open Liberty.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and
expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]
